# -----------------------
# STAGE 1: Build con Node
# -----------------------
FROM node:20-alpine AS build
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .
COPY . .
RUN pnpm build   # Esto genera la carpeta /app/dist

# -----------------------
# STAGE 2: Nginx para servir
# -----------------------
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
