name: Build and Deploy Extract WebContent Service

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'services/extract-webcontent/**'
      - 'shared/**'
      - '.github/workflows/build-extract-webcontent.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/extract-webcontent/**'
      - 'shared/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/extract-webcontent-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./services/extract-webcontent
        file: ./services/extract-webcontent/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  # Deploy to standard cloud provider (CPU-optimized)
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to production
      run: |
        echo "Deploying extract-webcontent service to production"
        # This service can run on any standard cloud provider
        # Example deployment commands here
