name: Build and Deploy Generate Description Service

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'services/generate-description/**'
      - 'shared/**'
      - '.github/workflows/build-generate-description.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/generate-description/**'
      - 'shared/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/generate-description-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./services/generate-description
        file: ./services/generate-description/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  # Deploy to RunPod or standard cloud (flexible)
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to production
      run: |
        echo "Deploying generate-description service to production"
        # Can be deployed to RunPod for GPU or standard cloud for CPU-only
        # Example deployment commands here
