name: Build Qwen Service

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref (branch or tag) to build"
        type: string
        default: main
      tag:
        description: "Extra tag for the image (optional, e.g: dev-2025-09-03)"
        type: string
        required: false

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  REPO: ${{ github.event.repository.name }}

jobs:
  build-qwen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: tags
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.REPO }}-svc-qwen"
          TAGS="${IMAGE}:sha-${GITHUB_SHA::7}"
          if [ "${{ inputs.ref }}" = "main" ]; then
            TAGS="${TAGS},${IMAGE}:latest"
          fi
          if [ -n "${{ inputs.tag }}" ]; then
            TAGS="${TAGS},${IMAGE}:${{ inputs.tag }}"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build & Push Qwen Service
        uses: docker/build-push-action@v6
        with:
          context: ./services/qwen-describe_image
          file: ./services/qwen-describe_image/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
